### ISSUE TITLE
Values in Region Geometric Information

### ISSUE THREAD

**Issue by Ago3** [LuoweiZhou/VLP#11]
Hi,

I noticed that the vector containing the region geometric information has 7 values instead of 5 ("top left and bottom right corner coordinates of the region bounding box and one value for its relative area", as described in the VLP paper). What are the last two values meant for? How can we compute them?

Thanks!

**Comment by LuoweiZhou** [comment]
The other two indicate the proposal confidence score and the most confident class prediction from the object detector: https://github.com/LuoweiZhou/VLP/blob/master/vlp/seq2seq_loader.py#L340

**Comment by Ago3** [comment]
Thank you so much!
