### ISSUE TITLE
File Not Found：feat_cls_1000_float16/cc_detection_vg_100dets_gvd_checkpoint_trainval

### ISSUE THREAD

**Issue by zhao1iang** [LuoweiZhou/VLP#13]
Thanks a lot for sharing this useful repo. we are trying to reproduce the finetuning result on flicker30k, but an error occurs which say "feat_cls_1000_float16/cc_detection_vg_100dets_gvd_checkpoint_trainval not found". I found this error is about this  line of code,  `parser.add_argument('--region_det_file_prefix', default='feat_cls_1000/coco_detection_vg_100dets_gvd_checkpoint_trainval', type=str)` . So where can I get access of "coco_detection_vg_100dets_gvd_checkpoint_trainval"? In my folder of feat_cls_1000, there are only "flickr30k_detection_vg_thresh0.2_feat_gvd_checkpoint_trainvaltest.h5" and  "trainval".

**Comment by zhao1iang** [comment]
After I modify this line of code `parser.add_argument('--region_det_file_prefix', default='feat_cls_1000/coco_detection_vg_100dets_gvd_checkpoint_trainval', type=str)` to `parser.add_argument('--region_det_file_prefix', default='feat_cls_1000/trainval', type=str) `, another error occurs  which say "FileNotFoundError: [Errno 2] No such file or directory: 'data/flickr30k/region_feat_gvd_wo_bgd/trainval/101669240_cls_prob.npy'"

**Comment by LuoweiZhou** [comment]
@zhao1iang Indeed I can only find `101669240.npy` but not `101669240_cls_prob.npy`.

@Palang2014 Could you see if you can find this file in our Azure storage? Thanks

**Comment by hamidpalangi** [comment]
Nope, I can only see `101669240.npy` in our storage. @zhao1iang you might want to follow the instructions Luowei has provided to extract the cls probs for this image, or if it is in training images, you can exclude it from valid images file you are providing as input.

**Comment by zhao1iang** [comment]
Thanks!
