### ISSUE TITLE
why the dimenson of region object labels is 1601?

### ISSUE THREAD

**Issue by Leoncatd** [LuoweiZhou/VLP#15]
Hi, I download the extracted features and find that the shape of region object labels is (100, 1601) for each image. Why there are so many classes?  I also notice that the shape of region geometric information is (100, 6) for each image. What does each value in the second dimension represent?

**Comment by LuoweiZhou** [comment]
@Leoncatd 1601 represents the 1600 object classes from [BUTD](https://github.com/peteanderson80/bottom-up-attention/blob/master/data/genome/1600-400-20/objects_vocab.txt) plus the background class (0), as we mentioned in the paper.

6 indicates the four bounding box coordinates (the top-left corner and the bottom-right corner), class index, and the objectness confidence score. You can find more details [here](https://github.com/LuoweiZhou/detectron-vlp/blob/master/tools/extract_features.py#L265).

**Comment by Leoncatd** [comment]
@LuoweiZhou Thanks : )
