### ISSUE TITLE
UniLM checkpoint is no longer available

### ISSUE THREAD

**Issue by GabrielLin** [LuoweiZhou/VLP#16]
# UniLM checkpoint
wget -O bert_save.tar.gz "https://onedrive.live.com/download?cid=E5364FD183A1F5BB&resid=E5364FD183A1F5BB%212016&authkey=AB5-lxzCkgpfLhg"

The above link is no longer anymore. Thanks.

**Comment by LuoweiZhou** [comment]
Please refer to this [issue](https://github.com/LuoweiZhou/VLP/issues/14) and you can also contact [Luowei](mailto:luozhou@umich.edu) for more details.

**Comment by GabrielLin** [comment]
@LuoweiZhou  OK, thanks for your reply.

**Comment by GabrielLin** [comment]
I saw that project. It seems that they have provided the link. What's different between theirs and yours?

> 
> Pre-trained Models
> We release a large cased UniLM model pre-trained with Wikipedia and BookCorpus corpora. The model is trained by using the same model configuration and WordPiece vocabulary as BERT. The model parameters can be loaded as in the fine-tuning code.
> 
> The links to the pre-trained models:
> 
> UniLMv1-large-cased: 24-layer, 1024-hidden, 16-heads, 340M parameters
>

**Comment by LuoweiZhou** [comment]
Ours is **base cased**, rather than **large cased**.

**Comment by GabrielLin** [comment]
Can I use the large cased model in this project?
