### ISSUE TITLE
Chinese image caption， In the result, multiple words of the same type appear

### ISSUE THREAD

**Issue by cylvzj** [LuoweiZhou/VLP#17]
Hello, I am using the COCO dataset,
A two-layer LSTM model, one layer for top-down attention, and one layer for language models.

Extracting words with jieba
I used all the words in the picture description that occurred more than 3 times as a dictionary file, and a total of 14,226 words.
words = [w for w in word_freq.keys () if word_freq [w]> 3]

After training the model, when using it, multiple words of the same type appear in the result, such as:

Note notebook laptop computer on bed
A little girl little girl girl standing together

How can I solve this problem?

**Comment by LuoweiZhou** [comment]
@cylvzj Is this issue related to this repo VLP? Usually, if you see repeated words, it indicates the training is incomplete and you might want to run it for a few more epochs.

**Comment by cylvzj** [comment]
@LuoweiZhou Thanks for the reply， Already trained 50,000 batches。

**Comment by LuoweiZhou** [comment]
@cylvzj I do not see how's this issue related to this repo. Please either try our VLP framework or make your question more specific.

**Comment by cylvzj** [comment]
Thanks for the reply

**Comment by cylvzj** [comment]
请问一下， 怎样减少奖励权重 （reduce the weight of the concept reward）?
