### ISSUE TITLE
adding specific tokens to vocabulary

### ISSUE THREAD

**Issue by xinyuwang1126** [LuoweiZhou/VLP#18]
Hi Luowei,

Thanks for sharing this repo! I am trying to adapt it to a specific task. In that task, I wish to remain some tokens unsplit (thousands of tokens). Is there a way that I could do that? I am trying to add tokens to bert vocabulary file but didn't find the file. Thanks and look forward to your reply!

**Comment by LuoweiZhou** [comment]
@xinyuwang1126 You can change the vocab by replacing the default [file](https://github.com/LuoweiZhou/VLP/blob/master/pytorch_pretrained_bert/tokenization.py#L37) with your customized vocab [file](https://github.com/LuoweiZhou/VLP/blob/master/pytorch_pretrained_bert/tokenization.py#L144). Then, you will need to modify the model [config](https://github.com/LuoweiZhou/VLP/blob/096661ed93ed9b76ee2e57f5800376d6fd859956/pytorch_pretrained_bert/modeling.py#L52) file and checkpoint (including both the .bin file and code) as well to map the old embeddings to your new vocab.

**Comment by xinyuwang1126** [comment]
got it, thank you!
