### ISSUE TITLE
MSCOCO data not found

### ISSUE THREAD

**Issue by xinyuwang1126** [LuoweiZhou/VLP#19]
Hi there,

I downloaded MSCOCO data and there seems to be missing data. So I removed and tried to redownload them. However, when I do
wget https://onedrive.live.com/download?cid=E5364FD183A1F5BB&resid=E5364FD183A1F5BB%212018&authkey=AHoTGG-7-6kwoAY
there is 404 not found error. 
Could you have a look at that and help me out? 
Thank you very much and stay healthy!

**Comment by LuoweiZhou** [comment]
@xinyuwang1126 Could you try it one more time? It happens sometimes as the connection to OneDrive is unstable.

**Comment by xinyuwang1126** [comment]
Hi Luowei,

I have tried again and it is still not working. Also, is it possible that data would be missing given that the link is unstable? I downloaded the data before as instructed, but when I tried to do inference on COCO it raised file not found error (some cls.h5 file)

**Comment by LuoweiZhou** [comment]
@xinyuwang1126 Sorry for the delay. Have you managed to download the data? Otherwise, please email me at luozhou@umich.edu and I can share it with you.
