### ISSUE TITLE
coco-caption commit is orphaned and can no longer be checked out

### ISSUE THREAD

**Issue by kracwarlock** [LuoweiZhou/VLP#21]
The repo uses https://github.com/kdexd/coco-caption/commit/de6f385503ac9a4305a1dcdc39c02312f9fa13fc. This doesn't exist anymore in the commit history https://github.com/kdexd/coco-caption/commits/master. It was likely force pushed upon or the corresponding branch was deleted. Due to this `CiderD(df=cached_tokens)` fails as the syntax has changed in the latest commit.

Another failure is:
```
    cocoEval = COCOEvalCap(coco, cocoRes, 'corpus')
TypeError: __init__() takes 3 positional arguments but 4 were given
```

Do you have a backup of that commit's tree that you can push? Or can you point to another commit that works with this repo?

**Comment by LuoweiZhou** [comment]
@kracwarlock Thanks for the feedback. I have pushed it to https://github.com/LuoweiZhou/coco-caption and updated the submodule accordingly.
