### ISSUE TITLE
Optimizer state dict for RL fine-tuning

### ISSUE THREAD

**Issue by aleSuglia** [LuoweiZhou/VLP#22]
Hi,

when you start the RL fine-tuning for image-captioning, do you load the optimiser weights that you used during the SL phase or you start with a brand-new optimiser that you use just for the RL training phase? In your current codebase I can see that you completely disabled the optimiser [state checkpointing](https://github.com/LuoweiZhou/VLP/blob/master/vlp/run_img2txt_dist.py#L599).

Many thanks,

Alessandro

**Comment by LuoweiZhou** [comment]
@aleSuglia No, it's a brand-new optimizer.
