### ISSUE TITLE
Finetuning and Testing on separate dataset

### ISSUE THREAD

**Issue by nikky4D** [LuoweiZhou/VLP#23]
Hi,

Would you have directions for finetuning and testing on a separate dataset? For instance, preparing the dataset, running the model on the dataset, and collecting error metrics?

Thanks

**Comment by LuoweiZhou** [comment]
@nikky4D You will need to add a new [dataset](https://github.com/LuoweiZhou/VLP/blob/master/vlp/run_img2txt_dist.py#L156), the corresponding [dataset source file](https://github.com/LuoweiZhou/VLP/blob/master/vlp/run_img2txt_dist.py#L149), and the feature files ([box](https://github.com/LuoweiZhou/VLP/blob/master/vlp/run_img2txt_dist.py#L179) and [feat](https://github.com/LuoweiZhou/VLP/blob/master/vlp/run_img2txt_dist.py#L180)) (using this [repo](https://github.com/LuoweiZhou/detectron-vlp) to extract).

**Comment by nikky4D** [comment]
Thanks for the info and the links. I appreciate it.
