### ISSUE TITLE
unable to Download feature from google drive

### ISSUE THREAD

**Issue by youngfly11** [LuoweiZhou/VLP#28]
Hi, 

the download feature link is not available for me and is very big, could you please provide another link? like baidu disk? 
When i click the google drive link, it will appear following error
![捕获](https://user-images.githubusercontent.com/24568308/92724208-d0197b00-f39c-11ea-8b88-d5bfd8ed0552.PNG)

Thanks

**Comment by aleSuglia** [comment]
Unfortunately looks like I'm not able to download Conceptual captions data as well. It asks me for my Microsoft credentials. Any thoughts?

**Comment by LuoweiZhou** [comment]
@youngfly11 Sorry for the inconvenience. I'm uploading the feature file to Baidu Pan, which will take some time (the uploading is quite slow actually). Will inform you when ready.

**Comment by LuoweiZhou** [comment]
@aleSuglia Somehow the link on CC is for embedding. I have updated the link in README (the same as https://onedrive.live.com/download?cid=E5364FD183A1F5BB&resid=E5364FD183A1F5BB%213781&authkey=ANA--esfJnWIKIE).

**Comment by LuoweiZhou** [comment]
@youngfly11 Sorry for the inconvenience. I was trying to upload the CC feature zip files which hit the upload limit (20G). I will try to find a workaround and let you know when the files are ready.
