### ISSUE TITLE
Multiple GPUs Support

### ISSUE THREAD

**Issue by idansc** [LuoweiZhou/VLP#3]
The provided fine-tuning scripts fails on multiple GPUs machine.
`Traceback (most recent call last):
  File "run_img2txt_dist.py", line 621, in <module>
    main()
  File "run_img2txt_dist.py", line 546, in main
    iter_bar.set_description('Iter (loss=%5.3f)' % loss.item())
ValueError: only one element tensors can be converted to Python scalars`

What is the recommended way to run a parallel training.  
Thanks :)

**Comment by LuoweiZhou** [comment]
Hi @idansc could you post your command here?

**Comment by idansc** [comment]
I tried the COCO caption script
`python vlp/run_img2txt_dist.py --output_dir $CHECKPOINT_ROOT/${checkpoint_coco_ce} \
    --model_recover_path $CHECKPOINT_ROOT/${checkpoint_cc}/model.30.bin \
    --do_train --new_segment_ids --always_truncate_tail --amp \
    --src_file $DATA_ROOT/COCO/annotations/dataset_coco.json \
    --file_valid_jpgs $DATA_ROOT/COCO/annotations/coco_valid_jpgs.json \
    --image_root $DATA_ROOT/COCO/region_feat_gvd_wo_bgd --enable_butd --s2s_prob 1 --bi_prob 0`

**Comment by LuoweiZhou** [comment]
@idansc you will need to set `--world_size` to the number of GPUs you have,  `--local_rank` and `--global_rank` to the index of the GPU. Say if you have two GPUs,
`--local_rank 0 --global_rank 0 --world_size 2`
`--local_rank 1 --global_rank 1 --world_size 2`
The command you posted works with one GPU (so by default `--local_rank -1 --global_rank -1 --world_size 1`, make sure you set `CUDA_VISIBLE_DEVICES=0`).

**Comment by LuoweiZhou** [comment]
I added a multi-GPU example here: https://github.com/LuoweiZhou/VLP#coco-captions

**Comment by idansc** [comment]
Thanks, this solves the issue. Small note `&` should be added between calls

**Comment by LuoweiZhou** [comment]
Nice catch, thanks!
