### ISSUE TITLE
Getting `No module named 'apex.optimizers'` error

### ISSUE THREAD

**Issue by gsrivas4** [LuoweiZhou/VLP#36]
Hello, Thanks for your work. 

Currently, I am trying to run inference on flickr features. I have installed apex as per the instructions in setup.sh. I have the same commit of apex (1603407bf49c7fc3da74fceb6a6c7b47fece2ef8) as mentioned in the setup.sh file. My pytorch version is 1.6.0+cu101, which is different from the one mentioned in misc/vlp.yml file. While installing apex I get following error message: `error: command 'gcc' failed with exit status 1`. When I try running the flickr inference code I get  below error:
```
Traceback (most recent call last):
  File "vlp/decode_img2txt.py", line 19, in <module>
    from pytorch_pretrained_bert.tokenization import BertTokenizer, WhitespaceTokenizer
  File "/home/default/ephemeral_drive/work/image_captioning/VLP/pytorch_pretrained_bert/__init__.py", line 6, in <module>
    from .optimization_fp16 import FP16_Optimizer_State
  File "/home/default/ephemeral_drive/work/image_captioning/VLP/pytorch_pretrained_bert/optimization_fp16.py", line 4, in <module>
    from apex.optimizers import FP16_Optimizer
ModuleNotFoundError: No module named 'apex.optimizers'
```

I tried installing the [latest apex version](https://github.com/NVIDIA/apex.git) as per the instructions [here](https://github.com/NVIDIA/apex/tree/master#linux). I get `Successfully installed apex-0.1` message, but when I run the inference code I get below error. 
```
Traceback (most recent call last):
  File "vlp/decode_img2txt.py", line 19, in <module>
    from pytorch_pretrained_bert.tokenization import BertTokenizer, WhitespaceTokenizer
  File "/home/default/ephemeral_drive/work/image_captioning/VLP/pytorch_pretrained_bert/__init__.py", line 6, in <module>
    from .optimization_fp16 import FP16_Optimizer_State
  File "/home/default/ephemeral_drive/work/image_captioning/VLP/pytorch_pretrained_bert/optimization_fp16.py", line 4, in <module>
    from apex.optimizers import FP16_Optimizer
ImportError: cannot import name 'FP16_Optimizer'
```
Seems, the optimizers are different in the latest apex commit. Would you recommend replacing the optimizer in your code with any of the [current ones](https://github.com/NVIDIA/apex/tree/master/apex/optimizers). Or, if you would have any other suggestion for me to resolve the issue. I am not able to use the conda environment you had mentioned as a requirement, as I am working on a controlled-access machine and I don't have the liberty to do all the installations.

**Comment by LuoweiZhou** [comment]
@gsrivas4 Yes, you need to adapt the code to the latest `apex`. Here are some changes I made towards another project (I will update it for this repo sometime during the holiday):
![image](https://user-images.githubusercontent.com/14948792/101991755-90945080-3c63-11eb-8004-0ba5902f6ed1.png)
![image](https://user-images.githubusercontent.com/14948792/101991761-9e49d600-3c63-11eb-9d6d-3e4844092f6d.png)
![image](https://user-images.githubusercontent.com/14948792/101991765-a7d33e00-3c63-11eb-9f59-4b00ea08db07.png)
![image](https://user-images.githubusercontent.com/14948792/101991772-b15ca600-3c63-11eb-8cfb-5d743274fa7f.png)
![image](https://user-images.githubusercontent.com/14948792/101991779-ba4d7780-3c63-11eb-90fd-7a2d62453272.png)
![image](https://user-images.githubusercontent.com/14948792/101991748-84a88e80-3c63-11eb-8a5f-54fe08129f45.png)

**Comment by LuoweiZhou** [comment]
Also, to allow `apex` to function appropriately, you need to use the same `CUDA` to compile `pytorch` and `apex`.

**Comment by gsrivas4** [comment]
Thanks @LuoweiZhou for the edit suggestions. I will make these edits and get back to you if I get any more errors, or otherwise.

**Comment by Leoncatd** [comment]
In the latest APEX release, FP16_Optimizer has been moved to CONTRIB/Optimizers; so you can try:
`from apex.contrib.optimizers import FP16_Optimizer`

Maybe you can get more information from [https://github.com/NVIDIA/apex/issues/699](url)

**Comment by gsrivas4** [comment]
@Leoncatd I am using CONTRIB/Optimizers right now and that seems to be working. Thanks you!
