### ISSUE TITLE
When will you release the visual feature detectron code?

### ISSUE THREAD

**Issue by yuewang-cuhk** [LuoweiZhou/VLP#9]
Hi Luowei,
     Recently I have been trying to extract detectron visual features following your guideline [here](https://github.com/LuoweiZhou/VLP/issues/7). But I still cannot replicate the features. I use the recommended [docker image](https://hub.docker.com/r/housebw/detectron) and refer to the preliminary scripts you send me by email. However, your script `extract_features_luowei.py` is actually incompatible with the detectron model in the [housebw's repo](https://github.com/the-house-of-black-and-white/Detectron/tree/master/detectron). For example, the `im_detect_bbox` method (in the figure below) should be imported from `core.test` instead of `core.test_engine`. 
![67132010-14c08480-f1d5-11e9-876d-fc8608108c5d](https://user-images.githubusercontent.com/8224463/67750483-4275bb00-fa6a-11e9-8754-8b3f9fb5334e.png)

Actually, I also find several other incompatibility issues when trying to run your code inside the provided docker environment. Even after I fixed some incompatibility issues and run the code successfully, I encounter such errors: 
```
WARNING cnn.py:  40: [====DEPRECATE WARNING====]: you are creating an object from CNNModelHelper class which will be deprecated soon. Please use ModelHelper object with brew module. For more information, please refer to caffe2.ai and python/brew.py, python/brew_test.py for more information.
INFO net.py:  59: Loading weights from: /export/home/vlp_data/e2e_faster_rcnn_X-101-64x4d-FPN_2x.pkl
I1029 08:52:12.747747  2485 net_dag_utils.cc:118] Operator graph pruning prior to chain compute took: 0.000186569 secs
I1029 08:52:12.747993  2485 net_dag.cc:61] Number of parallel execution chains 36 Number of operators = 371
I1029 08:52:12.770298  2485 net_dag_utils.cc:118] Operator graph pruning prior to chain compute took: 0.000165061 secs
I1029 08:52:12.770571  2485 net_dag.cc:61] Number of parallel execution chains 30 Number of operators = 358
/export/home/vlp_data/coco_raw/coco_tiny/COCO_test2014_000000000001.jpg
terminate called after throwing an instance of 'caffe2::EnforceNotMet'
  what():  [enforce fail at blob.h:94] IsType<T>(). wrong type for the Blob instance. Blob contains nullptr (uninitialized) while caller expects caffe2::Tensor<caffe2::CUDAContext> .
Offending Blob name: gpu_0/rois_fpn2.
Error from operator: 
input: "gpu_0/fpn_res2_2_sum" input: "gpu_0/rois_fpn2" output: "gpu_0/roi_feat_fpn2" name: "" type: "RoIAlign" arg { name: "pooled_h" i: 7 } arg { name: "sampling_ratio" i: 2 } arg { name: "spatial_scale" f: 0.25 } arg { name: "pooled_w" i: 7 } device_option { device_type: 1 cuda_gpu_id: 0 }
*** Aborted at 1572339134 (unix time) try "date -d @1572339134" if you are using GNU date ***
terminate called recursively
terminate called recursively
PC: @     0x7fe85f011428 gsignal
*** SIGABRT (@0x9b5) received by PID 2485 (TID 0x7fe7c0ffd700) from PID 2485; stack trace: ***
    @     0x7fe85f3b7390 (unknown)
    @     0x7fe85f011428 gsignal
    @     0x7fe85f01302a abort
    @     0x7fe8590bf84d __gnu_cxx::__verbose_terminate_handler()
terminate called recursively
    @     0x7fe8590bd6b6 (unknown)
    @     0x7fe8590bd701 std::terminate()
    @     0x7fe8590e8d38 (unknown)
    @     0x7fe85f3ad6ba start_thread
    @     0x7fe85f0e341d clone
    @                0x0 (unknown)
Aborted (core dumped)
```

Due to these **incompatibility issues,** I find it pretty difficult to extract the same visual features as yours. But if we use other detectron codes like detectron2 or mmdetection, we cannot use your pre-trained models. Therefore,  I would like to ask when you can fully release your detectron code (code & python environment), which will be extremely helpful for those planning to apply your VLP model into their own datasets like me. Look forward to your reply:)

**Comment by leotam** [comment]
The paper states "represent each input image as 100 object regions extracted from a variant of Faster R- CNN (Ren et al. 2015) pre-trained on Visual Genome (Krishna et al. 2017; Anderson et al. 2018)" so actually this repo https://github.com/peteanderson80/bottom-up-attention should be used to generate the features?

**Comment by LuoweiZhou** [comment]
Sorry for the delay due to my traveling. Our implementation is similar to the one used in Pythia. I will upload the full code around mid-Nov.

**Comment by yuewang-cuhk** [comment]
@leotam Hi, I have used the BUTD model (a [docker image](https://hub.docker.com/r/airsplay/bottom-up-attention) provided by airsplay) to extract the detection features. But I still feel that it might not generate the same features as the authors did. (They use facebooks' detection tool and pythia). Am I correct? @LuoweiZhou 
Look forward to the release of the full feature extraction code. Thanks a lot!

**Comment by LuoweiZhou** [comment]
Yes, the pre-trained VLP models would not work with features extracted from a different Detectron model.

**Comment by LuoweiZhou** [comment]
The code is now available here: https://github.com/LuoweiZhou/detectron-vlp

**Comment by sgdgp** [comment]
@yuewang-cuhk Were you able to fix the `Offending Blob name: gpu_0/rois_fpn2.` issue ?
I am facing the same issue currently.

**Comment by LuoweiZhou** [comment]
@sgdgp  Could you provide more details on how you install Caffe2 and Detectron? The feature extraction repo is based on the Detectron repo from [2018 May](https://github.com/LuoweiZhou/detectron-vlp/commit/557f73294f4d8ccf89851ae9b3bbba1cd8f38ea8) and this may account for the compatibility issue. So you might want to compare the differences in terms of Caffe2/Detectron installation (see the full history [here](https://github.com/facebookresearch/Detectron/commits/master/INSTALL.md)).
